services:
  api:
    depends_on: 
      db:
        condition: service_healthy
        restart: true
    build: .
    image: crud_api:1
    container_name: api
    volumes:
      - .:/app
      - /app/node_modules # Avoid overwriting installed node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env
    command: ["sh", "./docker-entrypoint.sh"]
  db:
    image: postgres:17-alpine3.21
    env_file:
      - ./.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
